### ISSUE TITLE
get node runs details using pychef

### ISSUE THREAD

**Issue by siddhu93** [coderanger/pychef#77]
We are trying to fetch details from chef "reports API" call using pychef, i am using the below code for API call.

import chef
with chef.ChefAPI('https://chef-server/organizations/devopsorg', 'devopsuser.pem', 'devopsuser', ssl_verify=False):
    api= chef.ChefAPI.get_global()
    print api
    print api["/reports/nodes/chefnode1/runs"]

I could able to fetch other chef server API form organization end but not "/organizations/ORG_NAME/reports/nodes/NODE/runs".
Please suggest us any way for handling this

**Comment by coderanger** [comment]
By default Chef Server does not save that information. It is part of the older Chef Reporting commercial addon and the newer Chef Automate system. As I've never used either, there is no direct API support for those in PyChef but you can always use the raw API object to make simple requests yourself. For example, looking at https://docs.chef.io/api_reporting.html#reports-nodes-node-runs you could use `api['/reports/nodes/foo.example.com/runs']` to get a list of the run IDs for that node.

**Comment by coderanger** [comment]
Sorry, I realize I didn't read this carefully enough and you might not be the same person as in the SO question. About the URIs, the thing in the `api[]` gets appended to the base URL you give in the `ChefAPI` constructor so if you want to access multiple orgs you can either give a base URL like `https://chef-server/` (though most PyChef objects won't work with this API object since they expect the base URL to point at the org) or make multiple API objects.
